[project]
name = "dcs-campaigns"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "luadata>=1.0.5",
]

[dependency-groups]
dev = [
    "ruff>=0.9.8",
]
